# Bu cloudbuild.yaml dosyası, projeyi bir Docker imajı olarak paketler
# ve Google Container Registry'ye gönderir. VM kurulumu için kullanılır.

steps:
# 1. Adım: Docker imajını inşa et ve etiketle
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/video-fabrikasi/video-fabrikasi-servisi:latest', '.']

# 2. Adım: İnşa edilen imajı Container Registry'ye gönder
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/video-fabrikasi/video-fabrikasi-servisi:latest']

# İnşaat bittiğinde, bu imajı sakla
images:
- 'gcr.io/video-fabrikasi/video-fabrikasi-servisi:latest'

